modules:
- name: runtime
  config:
    '@type': cosmos.app.runtime.v1alpha1.Module
    app_name: JanctionApp
    begin_blockers:
    - distribution
    - staking
    - videoRendering
    end_blockers:
    - staking
    - videoRendering
    init_genesis:
    - auth
    - bank
    - distribution
    - staking
    - genutil
    - videoRendering
    override_store_keys:
    - kv_store_key: acc
      module_name: auth
- name: auth
  config:
    '@type': cosmos.auth.module.v1.Module
    bech32_prefix: janction
    module_account_permissions:
    - account: fee_collector
    - account: distribution
    - account: bonded_tokens_pool
      permissions:
      - burner
      - staking
    - account: not_bonded_tokens_pool
      permissions:
      - burner
      - staking
    - account: videoRendering
      permissions:
      - staking
      - minter
      - burner
      - bank
- name: bank
  config:
    '@type': cosmos.bank.module.v1.Module
    blocked_module_accounts_override:
    - auth
    - distribution
    - bonded_tokens_pool
    - not_bonded_tokens_pool
- name: staking
  config:
    '@type': cosmos.staking.module.v1.Module
- name: distribution
  config:
    '@type': cosmos.distribution.module.v1.Module
- name: consensus
  config:
    '@type': cosmos.consensus.module.v1.Module
- name: genutil
  config:
    '@type': cosmos.genutil.module.v1.Module
- name: tx
  config:
    '@type': cosmos.tx.config.v1.Config
- name: videoRendering
  config:
    '@type': janction.videoRendering.module.v1.Module
    path: /Users/rodrigoacosta/.janctiond
