name: Build Janction
on: ["push"]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64]
        targetos: [darwin, linux]
        include:
          - targetos: darwin
            arch: arm64
    name: janction ${{ matrix.arch }} for ${{ matrix.targetos }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v6
        with:
          go-version: "1.21"
          check-latest: true
        env:
          GOOS: ${{ matrix.targetos }}
          GOARCH: ${{ matrix.arch }}

      - name: Compile janction
        run: |
          go mod download
          cd cmd/janctiond
          go build .

      - uses: actions/upload-artifact@v4
        with:
          name: janctiond ${{ matrix.targetos }} ${{ matrix.arch }}
          path: cmd/janctionid/janctiond
