name: Tests
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}-test
  cancel-in-progress: true

jobs:
  test-janctiond:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          check-latest: true
          cache: true
          cache-dependency-path: go.sum
      - name: test block creation
        run: |
          make install
          make init
          janctiond start &
          JANCTIOND_PID=$!
          cnt=0
          while ! janctiond query block --type=height 5; do
            cnt=$((cnt + 1))
            if [ $cnt -gt 30 ]; then
              kill -9 "$JANCTIOND_PID"
              exit 1
            fi
            sleep 1
          done
          kill -9 "$JANCTIOND_PID"
